DROP TABLE IF EXISTS ACCOUNT;

CREATE TABLE ACCOUNT
(
    ID LONG NOT NULL PRIMARY KEY,
    USERNAME VARCHAR(255) NOT NULL,
    HASHED_PASSWORD VARCHAR(60) NOT NULL
);

CREATE INDEX username_idx ON ACCOUNT(USERNAME);